### ISSUE TITLE
Utility function to escape text

### ISSUE THREAD

**Issue by lukepighetti** [simolus3/sqlite3.dart#100]
I'm trying to store json strings in sqlite, and it doesn't like the backslash in `{\"foo\":\"bar\"}`

1) do you know of any resources that describe how to escape json strings before storing in sqlite?

2) would it be within scope of this package to provide a utility function for this use case?

**Comment by simolus3** [comment]
> do you know of any resources that describe how to escape json strings before storing in sqlite?

String literals should be written as single quotes, so you can use a double quote in a string without a backslash. If you want to include a single quote in a string, use two single quotes (`''`) as an escape. From [here](https://www.sqlite.org/lang_expr.html):

> A string constant is formed by enclosing the string in single quotes ('). A single quote within the string can be encoded by putting two single quotes in a row - as in Pascal. C-style escapes using the backslash character are not supported because they are not standard SQL. 

> would it be within scope of this package to provide a utility function for this use case?

Personally, I want to encourage the use of prepared statements with string variables. IMHO, using string interpolation in SQL queries is always a dangerous game since it's just too easy to overlook an SQL injection vulnerability.

So, instead of doing:

```dart
  db.execute('INSERT INTO my_table VALUES (${escape(someJsonString)})');
```

please use

```dart
  final stmt = db.prepare('INSERT INTO my_table VALUES (?)');
  stmt.execute([someJsonString]);
  stmt.dispose();
```

**Comment by lukepighetti** [comment]
Thank you for the thorough response. After writing this issue I used the string variables feature you outlined above and it resolved my issue. Thank you.
