### ISSUE TITLE
Trouble creating transaction

### ISSUE THREAD

**Issue by lukepighetti** [simolus3/sqlite3.dart#103]
I'm trying to create a dynamic version of this query so that I can delete multiple items with a single transaction. It appears to render properly, but returns an error `Invalid argument (sql): Had an unexpected trailing statement`

```sql
BEGIN TRANSACTION;

DELETE FROM table_set
WHERE name="name" AND type="MyBuiltEnum" AND value="FOO";

DELETE FROM table_set
WHERE name="name" AND type="MyBuiltEnum" AND value="BAR";

DELETE FROM table_set
WHERE name="name" AND type="MyBuiltEnum" AND value="BAZ";

COMMIT;
```

Here's what I have so far

```dart
    final table = 'table_set';
    final values = ['FOO', 'BAR', 'BAZ'];

    execute('''
      BEGIN TRANSACTION;

      ${values.map((_) => 'DELETE FROM ${table.set} WHERE name=? AND type=? AND value=?;').join('\n')}

      COMMIT;
      ''', [
      for (final value in values) ...[name, type, value]
    ]);

```

However, it produces this error

```
  Invalid argument (sql): Had an unexpected trailing statement.: "      BEGIN TRANSACTION;\n\n      DELETE FROM main_set WHERE name=? AND type=? AND value=?;\nDELETE FROM main_set WHERE name=? AND type=? AND value=?;\nDELETE FROM main_set WHERE name=? AND type=? AND value=?;\n\n      COMMIT;\n      "
  package:sqlite3/src/ffi/impl/database.dart 242:11  DatabaseImpl._prepareInternal
  package:sqlite3/src/ffi/impl/database.dart 109:19  DatabaseImpl.prepare
  package:sqlite3/src/ffi/impl/database.dart 97:20   DatabaseImpl.execute
  package:kv_sqlite/src/extensions.dart 101:5        SetDatabaseExtensions.deleteSetElements
  package:kv_sqlite/src/kv_set.dart 64:12            KvSet.removeAll
  test/kv_sqlite_test.dart 128:13                    main.<fn>.<fn>
  test/kv_sqlite_test.dart 85:33                     main.<fn>.<fn>
```

Extracting from there, the query generated is:

```sql
      BEGIN TRANSACTION;

      DELETE FROM main_set WHERE name=? AND type=? AND value=?;
DELETE FROM main_set WHERE name=? AND type=? AND value=?;
DELETE FROM main_set WHERE name=? AND type=? AND value=?;

      COMMIT;
      
```

and the generated arguments are

```
["name", "MyBuiltEnum", "FOO", "name", "MyBuiltEnum", "BAR", "name", "MyBuiltEnum", "BAR"]
```

which should render as

```sql
BEGIN TRANSACTION;

DELETE FROM table_set WHERE name="name" AND type="MyBuiltEnum" AND value="FOO";
DELETE FROM table_set WHERE name="name" AND type="MyBuiltEnum" AND value="BAR";
DELETE FROM table_set WHERE name="name" AND type="MyBuiltEnum" AND value="BAZ";

COMMIT;
      
```

**Comment by simolus3** [comment]
sqlite3's API can only prepare one statement at a time (and a `PreparedStatement` instance from this package wraps one such statement too). In your case though, there are five statements (begin, 3x delete, commit).

If you give sqlite3 multiple statements in a prepare call, it will only scan the first statement and stop there (so the native sqlite3 APIs would only give you `BEGIN TRANSACTION` and silently ignore the rest). This is super confusing, so this package attempts to check that the query you issued ends with the first statement (so you get an exception instead of silently ignored statements, an improvement IMO).

Now, how to solve this. A neat thing about prepared statements is that you can prepare (= compile) them once and run them multiple times, which comes in handy for your deletes. So I'd probably write it like this:

```dart
final delete =
    db.prepare('DELETE FROM table_set WHERE name = ? AND value = ?;');

db.execute('BEGIN;');
delete.execute(['MyBuiltEnum', 'FOO']);
delete.execute(['MyBuiltEnum', 'BAR']);
delete.execute(['MyBuiltEnum', 'BAZ']);
db.execute('COMMIT;');

delete.dispose();
```

Obviously you probably need something more dynamic with loops for `delete.execute`, but I think you'll get the point :D Statements without any parameters can just be directly executed on the database (doesn't make too much sense to prepare those).

Alternatively, you could use `prepareMultiple` to get a list of statements from a single string, but using that will probably lead to a more complicated implementation for your case.
