### ISSUE TITLE
Execute should return rows affected

### ISSUE THREAD

**Issue by cornfeedhobo** [simolus3/sqlite3.dart#109]
I notice in other languages that sqlite libraries return modified row counts from execute(). Would you be open to adding this?

**Comment by simolus3** [comment]
You can call [`getUpdatedRows()`](https://pub.dev/documentation/sqlite3/latest/sqlite3.common/CommonDatabase/getUpdatedRows.html) on the database to get this information. 

In my opinion, I think this would be a bit weird to have on `execute()` because:

1. Some statements (like `CREATE TABLE`) don't change the last updated rows counter, so `execute` would then confusingly report the amount of rows changed by the previous statement.
2. This functionality is broken when passing multiple statements to `execute()`: E.g. if I did `execute('UPDATE foo SET bar = 1; DELETE FROM foo WHERE id < 10')`, I would expect `execute` to return the total number of rows affected. But we can't get this information out of sqlite, we can only know how many rows where changed by the last statement.

So, given that this return value is easy to trick, I think it shouldn't be part of `execute` directly. If you need it for your application and you know you're not going to misuse it, you can add an extension for it:

```dart
extension on CommonDatabase {
  int executeWithModified(String sql) {
    execute(sql);
    return getUpdatedRows();
  }
}
```

**Comment by cornfeedhobo** [comment]
> 1. Some statements (like `CREATE TABLE`) don't change the last updated rows counter, so `execute` would then confusingly report the amount of rows changed by the previous statement.
> 2. This functionality is broken when passing multiple statements to `execute()`: E.g. if I did `execute('UPDATE foo SET bar = 1; DELETE FROM foo WHERE id < 10')`, I would expect `etxecute` to return the total number of rows affected. But we can't get this information out of sqlite, we can only know how many rows where changed by the last statement.

I don't follow your logic here. For example, [the golang library requires this](https://cs.opensource.google/go/go/+/go1.18.3:src/database/sql/driver/driver.go;l=316), which makes me think that this is a choice, not a real technical limitation.


> So, given that this return value is easy to trick, I think it shouldn't be part of `execute` directly. If you need it for your application and you know you're not going to misuse it, you can add an extension for it:
> 
> ```dart
> extension on CommonDatabase {
>   int executeWithModified(String sql) {
>     execute(sql);
>     return getUpdatedRows();
>   }
> }
> ```

Yes, but doesn't this break down in any `async` uses, since you're requesting the library sort it out at the database level and thus inviting a race condition?
