### ISSUE TITLE
Can you add a OSI license to this library

### ISSUE THREAD

**Issue by ZiiwareJordanc** [simolus3/sqlite3.dart#143]
I want to use import this library for use in a production app we have at my company as this seems to be better maintained than the other sqlite cipher library. 
However i don't quite feel comfortable importing something that cannot be verified as open source into something that affects more than just me.

**Comment by simolus3** [comment]
Which package are you referring to,  `sqlcipher_flutter_libs`? The package itself is licensed under MIT, but it bundles SQLCipher and parts of OpenSSL so I've added those licenses as well.

**Comment by ZiiwareJordanc** [comment]
Yes, i am referring to sqlcipher_flutter_libs (https://pub.dev/packages/sqlcipher_flutter_libs).
pub.dev in the score section still has the license marked as un-recognized so i figured id make a post.

**Comment by simolus3** [comment]
I'm following the advice [from here](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#adding-licenses-to-the-license-file) to include multiple licenses for the plugin. It's understandable (but unfortunate) that pub.dev can't pick that up, but since this plugin statically links the other software as well I think that's the way it needs to be done.

So the story is that, if you depend on `sqlcipher_flutter_libs`, you're linking code from three projects (OpenSSL, SQLCipher,  `sqlcipher_flutter_libs`). I think it's best if I add all these components to the `LICENSE` file here, since the licenses for OpenSSL and SQLCipher would not show up in the license page for apps otherwise - which means that apps built with that package would violate the two licenses by default. That's arguably much worse.

I can understand the uneasy feeling about this, but I can't sweep the two additional licenses under the floor either. The code in `sqlcipher_flutter_libs` is MIT licensed, OpenSSL is under the Apache license and SQLCipher has [this weird license](https://www.zetetic.net/sqlcipher/license/) that looks like a 3-clause BSD with an "All rights reserved" clause at the beginning. That's what it says in the `LICENSE` file added to this repository as well, I can't give any advice on what that means for downstream users.
