### ISSUE TITLE
Detect wasm version

### ISSUE THREAD

**Issue by alextekartik** [simolus3/sqlite3.dart#154]
Hi Simon, I try to follow your sqlite3 updates for both the package and the wasm binary. Sometimes we might have a difference between the sqlite3 package version used and the wasm installed binary which can lead to the following bug: https://github.com/tekartik/sqflite/issues/974. Is there a way to detect from the web side (after loading the wasm binary) the version of the wasm library loaded and get the sqlite3 package version - still from the web so that means an addionnal exported constant) ? By doing so we could inform the developer to reinstall the latest wasm (I have a small tool that download your binary but nothing prevent the user from having an old wasm installed). But sometimes the package will be updated but still being compatible with the existing wasm. Well I'm not sure I'm clear but I just wonder if you either think about how making sure the installed version are compatible or whether it is just a developer pb.

**Comment by simolus3** [comment]
The intention was for changes to be backwards compatible, so it looks like I've slipped up here -- sorry!

I think we can provide the expected version as a constant in the library - you can get the actual version through `CommonSqlite.version` and compare them.

**Comment by simolus3** [comment]
So I've just realized that this wouldn't work of course since the error happened when instantiating `CommonSqlite` -- oops! I think the original problem can reasonably be considered a bug in this package since we should support older versions in general. That was fixed in 4d4251d4cfc201880d748856bafb90b6abf6ef9c.

The desired behavior in this package is to throw an exception suggesting a upgrade for `sqlite3.wasm` when an unsupported feature is used, but to generally work with older versions of the compiled library. That's also the intention that you had for the sqflite wrapper, right? Do you still need an API to check the expected version if older versions are supported?

**Comment by alextekartik** [comment]
Yes the intention is to be backward compatible as much as possible and yeah bug might happen but since the developer should see a relevant exception in this case while developing, I'm perfectly fine in having him manually update the wasm binary when he sees obvious crashes. I guess you might have similar issue with drift on the web. Closing the issue, thanks.
