### ISSUE TITLE
SpatiaLite

### ISSUE THREAD

**Issue by lukepighetti** [simolus3/sqlite3.dart#16]
Hi there, I'm just finding this project and I'm trying to understand it better. It looks like it's a quick way to bring in custom versions of SQLite for use in Flutter? I am trying to get access to SpatiaLite on Flutter for iOS and Android. Is that within the scope of the project? What's needed on my end to start querying SpatiaLite in my project using this project?

**Comment by simolus3** [comment]
This project includes the `sqlite3` package, which is a wrapper around sqlite3's C api. It also provides the `sqlite3_flutter_libs` package, which provides native sqlite3 libraries for Flutter projects.
To use a custom sqlite3 version or extension in your project, you can use the `sqlite3` package with custom buildscripts to compile and include SpatiaLite in your project. You shouldn't use `sqlite3_flutter_libs` in that case, you need something custom for your use case.

**Comment by lukepighetti** [comment]
Are there any examples available for how to build these binaries for iOS and Android? Do you have them hosted somewhere? Would sqlite3_flutter_libs be interested in hosting and maintaining a version of SpatiaLite for use with `sqlite3`? Please excuse my ignorance, trying to get an idea of what's going on here.

**Comment by simolus3** [comment]
> Would sqlite3_flutter_libs be interested in hosting and maintaining a version of SpatiaLite for use with `sqlite3`?

If it did, every app depending on `sqlite3_flutter_libs` would include SpatiaLite binaries, which is not what we want. We'd probably need another package that's similar to `sqlite3_flutter_libs` but includes a SpatiaLite shared libraries instead of sqlite. I don't want to maintain that package, but I can help you set it up.

> Are there any examples available for how to build these binaries for iOS and Android?

For iOS, you might be able to just use the SpatiaLite pod to include binaries. It's probably more complicated on Android. For `sqlite3_flutter_libs`, I maintain an [Android library](https://github.com/simolus3/sqlite-native-libraries) that only includes the precompiled binaries (shipping sources and making users compile them turned out to be rather unstable). `sqlite3_flutter_libs` then includes that library in its `build.gradle`. SpatiaLite contains some makefiles that you can probably invoke from the NDK. You can mostly use the NDK guides as an example, but keep in mind that you don't need JNI for `dart:ffi`.

**Comment by lukepighetti** [comment]
Alright I think I'm finally getting aligned. Sounds like forking `sqlite3_flutter_libs` into something like `spatialite_flutter_libs` and getting the binaries building should provide a solution that Just Works™. It also sounds like you don't have any interest in maintaining that if I end up finding success with it, which is obviously fine. 

That said, if I were going to give you a sales pitch on maintaining it, it would be something like: SpatiaLite is an extremely robust geo server that should work with any generalized sqlite driver using raw queries. We don't have anything that comes close in Flutter packages at the moment and it would add an incredible amount of functionality to `sqlite3` package for seemingly cheap.

Let me see what I can do here.

**Comment by lukepighetti** [comment]
Yyyyeeeeah I'm going to give up on this for now. Will reopen if I get the fire to move forward.

**Comment by captfresh** [comment]
@lukepighetti Hi, did you move forward with this by any chance?
We have a similar use case with us now, and are trying to see if we can get some available solutions before jumping in to building one of our own.
Thanks

**Comment by sodafago** [comment]
> @lukepighetti Hi, did you move forward with this by any chance? We have a similar use case with us now, and are trying to see if we can get some available solutions before jumping in to building one of our own. Thanks

@captfresh I am also looking for a solution to store and process geodata in flutter, first of all I need ios and android. I'm trying to figure out if it's a good idea to try to raise SpatiaLite on these platforms, how are you doing with this?

**Comment by stanimeros** [comment]
@lukepighetti I am also interested on integrating spatialite in flutter somehow. Have you figured it out?
