### ISSUE TITLE
Is publishing an app with sqlite3_flutter_libs on the App Store allowed?

### ISSUE THREAD

**Issue by manuel-escola** [simolus3/sqlite3.dart#165]
I am not 100% sure, but I think Apple imposes restrictions on apps shipping interpreters. Do you know if the app should be approved in case it works correctly (i.e. no crashes)?

**Comment by simolus3** [comment]
While `sqlite3` is technically an interpreter / compiler, I'm not aware of any issues that have happened due to this in the review process or in the app itself. In my understanding the review guidelines allow this unless you start downloading code (which I guess includes SQL under that definition) to circumvent the review process.
