### ISSUE TITLE
An int column accepts strings - windows. Returns ints or strings.

### ISSUE THREAD

**Issue by brilliapps** [simolus3/sqlite3.dart#170]
Just quickly issue report.

A new version of sqlite3 installed, maybe the newest. I am suprised. Platform where it happened: Windows (flutter run -d windows): By mistake i made a column int not string, but it accepted ints and strings (example of accepted wrong value in that column "descchange1688999391843"). Then when a row was read the type of of data was int when it was number and as i quess string when it was string (not tested reading but it stored string so it is a string). Now i see the effects by accident. It looks like, no error was thrown when string was stored in the column.
I don't know if it is a sqlite feature, or for example some sqlite3 dart library implementation bug in this particular aspect.
sqlite3.dll version 3.40.0.0, copyrights has in a longer url "sqlite.org", 2.06 MB - don't remember how i obtained it but it was probably copied this year into a directory where i wanted it to be and stays there.
No itention to confuse anybody or waste your time. Just reporting what is see.
Apart from this problem the rest is ok.

**Comment by simolus3** [comment]
> I don't know if it is a sqlite feature, or for example some sqlite3 dart library implementation bug in this particular aspect.

This is actually sqlite3 working as intended and not a weirdness caused by this library. sqlite is built with [flexible typing](https://sqlite.org/flextypegood.html), which means that it will attempt to transform values into the desired type, but leave them alone otherwise.

If you want rigid checks for values inserted into a table, you can make the [table STRICT](https://sqlite.org/stricttables.html) (which is what I prefer as well, personally), but it's not enabled by default in sqlite3.

**Comment by brilliapps** [comment]
Thank you for your explanation and time, now i know.
