### ISSUE TITLE
`Database.lastInsertRowId` should `return` `int?`, instead of `int`

### ISSUE THREAD

**Issue by gintominto5329** [simolus3/sqlite3.dart#195]
Hi,

I noticed,
If NO `INSERT` op has happened on a newly created table, 0 is returned, which is correct.
But, 0 is also returned, when the insert op is the first insert of the session, may or may not be first row of the table, which is incorrect, and `null` should be returned, in this case, if possible, else please add docs.

thanks

**Comment by simolus3** [comment]
We call `sqlite3_last_insert_rowid` under the hood, which always returns an integer and so we can't return `null`.

> But, 0 is also returned, when the insert op is the first insert of the session, may or may not be first row of the table, which is incorrect

After the insert it should actually return the rowid of that insert, which is unlikely to be zero since these usually start at 1. Unless you're inserting to a `WITHOUT ROWID` or some virtual tables. I have clarified the documentation.
