### ISSUE TITLE
implement a `pkg:realm:Transaction` like class, simplifying `commit` and `rollback`

### ISSUE THREAD

**Issue by gintominto5329** [simolus3/sqlite3.dart#198]
Hi,

MongoDB's Realm package, has a [Transaction](https://pub.dev/documentation/realm/latest/realm/Transaction-class.html) class, returned by its Database-equivalent's [`beginWrite`](https://pub.dev/documentation/realm/latest/realm/Realm/beginWrite.html) method.

But, we should name it `beginWriteTransaction`, instead of `beginWrite`.

thanks

**Comment by simolus3** [comment]
This is a fairly low level library around sqlite3, so I think users should manage transactions themselves by calling `BEGIN` and `COMMIT` as necessary.

If we support transactions, every call on the database would have to wait for a transaction to be complete because transactions aren't separate connections (and so the call outside of the transaction would read data written in the transaction). With a synchronous API, this isn't possible.

**Comment by gintominto5329** [comment]
hi,

your are so quick, i must say.

> users should manage transactions themselves by calling BEGIN and COMMIT as necessary.

Using `db.execute` right?

thanks

**Comment by simolus3** [comment]
> How may I access the actual ffi bind-ed functions, if possible

Why would you want to do that? It requires allocating and freeing memory yourself, which this library takes care of. You can call [methods from this package](https://pub.dev/documentation/sqlite3/latest/sqlite3/sqlite3-library.html) which directly correspond to sqlite3 calls except that they wrap them in Dart types.

> Using `db.execute` right?

Exactly.
