### ISSUE TITLE
listening to database changes from a separate process 

### ISSUE THREAD

**Issue by albe-jj** [simolus3/sqlite3.dart#215]
I'm trying to listen for changes on a database table which are operated from a python process, however it seems like that drift `watch` function only gets triggered for changes to the database made by the same drift process which is listening . I tried also with an insert from a different dart process or a raw sql insert and I also don't get notified.

I'm using the code below to watch the last dataset added to the database from the python process. 

```dart
main() async {
  final db = await QdriveDb('etiket_db.sql', logStatements: true);

  final query = db.select(db.datasets)
    ..orderBy([
      (t) => OrderingTerm(expression: t.id, mode: OrderingMode.desc),
    ])
    ..limit(1);
  Stream<Dataset?> datasetStream = query.watchSingleOrNull();
  final datasetStreamSubscription = datasetStream.listen((Dataset? latestDataset) {
    print(latestDataset);
  });

  await Future.delayed(Duration(seconds: 2));
  db.into(db.datasets).insert(newDataset);
}
``` 

Is there anything wrong I'm doing? is it not possible to listen to changes from a different process?

**Comment by simolus3** [comment]
> is it not possible to listen to changes from a different process?

Not directly unfortunately. Drift's update mechanism doesn't use any special sqlite3 APIs at the moment, it just relies on statements cooperatively describing which tables they'll modify and which ones they're reading from.

sqlite does provide a raw update hook (which is not currently used in drift), but even that wouldn't solve this since it doesn't work across different database connections or processes. So the only way to solve this is to somehow make the processes talk to each other to share the updates they've made. You can use [notifyUpdates](https://drift.simonbinder.eu/api/drift/databaseconnectionuser/notifyupdates) on the database class to update streams when you have invalidated tables externally.
