### ISSUE TITLE
upgrading existing database 

### ISSUE THREAD

**Issue by mohammedX6** [simolus3/sqlite3.dart#217]
Looking on upgrading an existing database to include a new column in a specific table without deleting the database,
In android there is a onUpgrade

**Comment by simolus3** [comment]
These `onUpgrade` callbacks use the [user version](https://www.sqlite.org/pragma.html#pragma_user_version) pragma to keep track of version numbers. You can use `pragma user_version` to select the current version, and execute `praga user_version = 123` to set the current version in the database.

So to implement a migration, you'd load the existing version immediately after opening the database. Then, you check the version from the database with the expected version from your app, run the `ALTER` statements if necessary and finally use `pragma user_version = $version_in_app` so that the migration doesn't run after opening the database again.
