### ISSUE TITLE
sqlite3_flutter_libs 0.4.0

### ISSUE THREAD

**Issue by Milvintsiss** [simolus3/sqlite3.dart#22]
I'm getting this error when trying to open sqlite in memory on Android.

> Invalid argument(s): Failed to load dynamic library (dlopen failed: library "/data/data/com.milvintsiss.chronopsi/lib/libsqlite3.so" not found)

I'm using sqflite 1.3.2+3 and  moor: 3.4.0

Work fine with sqlite3_flutter_libs 0.3.0

**Comment by simolus3** [comment]
Thank you for reporting this error! It has been caused by a Gradle configuration mistake on my end. Apologies for the caused trouble.

I've now published version `3.34.1+1` of `eu.simonbinder:sqlite3-native-library` to maven central and `sqlite3_flutter_libs` version `0.4.0+1` to pub. Those versions should fix this problem, please let me know if the problem persists.

**Comment by Milvintsiss** [comment]
Thanks, worked like a charm 👍 

Thank you for developing moor, I'm using it for a cross-platform app (Android, iOS, MacOs, Windows, Linux) and it is always a pleasure to use it!
