### ISSUE TITLE
support `RETURNING row_id` for `INSERT`(in `CommonDatabase.execute` and `CommonPreparedStatement.execute`)

### ISSUE THREAD

**Issue by gintominto5329** [simolus3/sqlite3.dart#226]
hi,

I need to get the row-id of the latest inserted row .
We tried the lib.'s `CommonDatabase.lastInsertRowId` ,but its :
- resets on system::process end
- global/DB-level value ,not table-level/per-table
- multi-thread un-safe
- sequence un-safe
- overall unreliable

NOTE :the row-id column is always present in sqlite rows ,unless explicitly disabled.

Doc. : [www.sqlite.org/lang_returning](http://www.sqlite.org/lang_returning.html)
Guide : [www.stackoverflow.com/question/retrieve-inserted-id-after-inserting-row-in-sqlite-using-python/answer](https://stackoverflow.com/questions/6242756/how-to-retrieve-inserted-id-after-inserting-row-in-sqlite-using-python/60045014#60045014)

thanks

**Comment by simolus3** [comment]
I'm not sure what additional APIs from this package you're looking for. You can write an `INSERT ... RETURNING row_id` statement and then run it with `select` to get the returned row id.

**Comment by gintominto5329** [comment]
is it correct to use `select(` for non-`SELECT` queries ,
it seems like a leaky abstraction ,isn't it?

**Comment by simolus3** [comment]
> is it correct to use `select(` for non-`SELECT` queries ,

Yes. `select` can actually be used for all kinds of statements, even if they don't return any rows (the returned result set will just be empty in that case).

>  it seems like a leaky abstraction ,isn't it?

Leaky through its name?  It might be that this is a _missing_ abstraction, because `execute` suggests it can run all kinds of statements but `select` suggests it can only run `SELECT`s.

The name has been chosen because the particular API predates the support for `RETURNING` in sqlite3. I have added clarifying documentation comments in 44d78ee2dfa76a5c93e1679af764bb18ec793f77.
