### ISSUE TITLE
Differences between sqlite3_flutter_libs and sqlite3 releases

### ISSUE THREAD

**Issue by alextekartik** [simolus3/sqlite3.dart#228]
Hi Simon,
That is not an issue, I was just wondering what are the differences in the releases here:
https://github.com/simolus3/sqlite3.dart/releases

Some releases are labelled sqlite3_flutter_libs and some are labelled sqlite3 and I'm not sure what the differences are (especially regarding wasm binaries) and can they both be used in flutter or dart simple web app.

Thank you

**Comment by simolus3** [comment]
I'm always attaching the latest `sqlite3.wasm` whenever I do a release so that they're easier to find. I thought that might make things easier, but I can see how that could be confusing as well.

These are different releases because they're different packages, but the attached wasm modules are identical and both a suitable for both Flutter web and pure Dart web apps.
