### ISSUE TITLE
Does sqlite3_flutter_libs needs to support NNBD?

### ISSUE THREAD

**Issue by rubenferreira97** [simolus3/sqlite3.dart#23]
I am trying to migrate my project to NNBD. This package does not support NNBD (according to the https://pub.dev/packages/sqlite3_flutter_libs). My question is, does this package needs to support it so I can migrate my project to NNBD?

Accordingly with https://dart.dev/null-safety all my dependencies need to support it so I can have a project fully sound. I know this  might be a different type of project since it bundles sqlite3 libraries and intentionally contains no Dart code.

Sorry if this might be an idiotic question, but this is the last package that does not support NNBD from my dependency list. As far as I know since it does not contains dart code it should be fairly simple to place a NNBD tag right?

**Comment by simolus3** [comment]
I agree that the `sqlite3_flutter_libs` package should bump its minimal SDK constraint so that the migration tool stops complaining.

If you're not importing `package:sqlite3_flutter_libs` in your Dart code, starting the NNBD migration now is completely safe and you can run your app with strong null-safety if it's the only remaining dependency.

**Comment by simolus3** [comment]
I've just published `sqlite3_flutter_libs` version `0.4.1` that formally opts in to null-safety.
