### ISSUE TITLE
Cannot open encrypted database

### ISSUE THREAD

**Issue by itsJoKr** [simolus3/sqlite3.dart#234]
We have Isar database running SQLite engine, and want to replace critical queries with raw SQL using sqlite3.

In our tests, everything works fine if the database is not encrypted. But with encryption, the sqlite3 throws:
```
while preparing statement, file is not a database, file is not a database (code 26)
```

Looking at Isar source, nothing seems unusual (except the part that it is in Rust). It uses libsqlite3-sys and runs `("PRAGMA key = \"{}\"", encryption_key);` with no special setup.

With sqlite3, I'm using `sqlcipher_flutter_libs`. The `db.select('PRAGMA cipher_version;')` is not empty, meaning encryption is set up, but I get that exception.

This possibly is not issue with sqlite3, but likely I'm doing something wrong.

**Comment by simolus3** [comment]
Interesting. So are you sure you're using a matching encryption key and that the key is not transformed by Isar before reaching the pragma?

Also, using two copies of sqlite3 in the same process can lead to problems, but I think it should be fine here if Isar essentially links SQLCipher statically? If the symbols from the two sqlite3/SQLCipher copies are intertwined it will cause trouble since slightly incompatible versions are then calling internal functions of another.

**Comment by itsJoKr** [comment]
Actually, everything works here. I got something wrong in my test project.

I have no idea how Isar does it. It pretty much just includes Rust SQL cipher library and that's it. But queries seems slow, no idea why. I don't want to waste time on debugging Rust, it's easier to rewrite these queries in sqlite3. Thanks for the good work on open source.
