### ISSUE TITLE
A problem occurred configuring project ':sqlite3_flutter_libs'

### ISSUE THREAD

**Issue by budlight** [simolus3/sqlite3.dart#24]
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':sqlite3_flutter_libs'.
> Could not resolve all artifacts for configuration ':sqlite3_flutter_libs:classpath'.
   > Could not find com.google.prktobuf:protobuf-java:3.10.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/prktobuf/protobuf-java/3.10.0/protobuf-java-3.10.0.pom
       - https://jcenter.bintray.com/com/google/prktobuf/protobuf-java/3.10.0/protobuf-java-3.10.0.pom
     Required by:
         project :sqlite3_flutter_libs > com.android.tools.build:gradle:4.1.2 > com.android.tools.build:builder:4.1.2 > com.android.tools.ddms:ddmlib:27.1.2
> Could not get unknown property 'android' for project ':sqlite3_flutter_libs' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

this is in a new project setup with flutter 2.0

I'm not very familiar with the flutter plugin build process do I not know what else to provide.

**Comment by budlight** [comment]
example project generating this error for me

https://github.com/budlight/flutter_moor_test

**Comment by simolus3** [comment]
Thank you for publishing a repro! However, I can build your example project just fine. I cloned it and ran `flutter build apk` (I'm on Flutter version `2.0.1`).

> Could not find com.google.prktobuf:protobuf-java:3.10.0.

This looks like a typo, it should probably `com.google.protobuf`. Weirdly, this project does not use or depend on Protobuf (at least not directly).
From the "Required by" description, it looks like that is pulled in from `com.android.tools.ddms:ddmlib`, but that does declare a proper dependency as far as I can see. Since it's a transitive dependency of `com.android.tools.build:gradle` (which is used to build all Android apps and libraries) _and_ I found zero results of that typo on Google, I think this might be an issue with your build setup. Does the build work on another machine?

You might want to try running the build with a fresh Gradle cache in case a local dependency is broken for you. Can you try renaming `~/.gradle` to `~/.gradle_backup` and run the build again? You can revert the name change afterwards to avoid making things worse :D

**Comment by budlight** [comment]
it does run correctly on my mac, it seems like it was disk corruption issue on my windows pc.
