### ISSUE TITLE
Supported sqlite extensions

### ISSUE THREAD

**Issue by MobiliteDev** [simolus3/sqlite3.dart#25]
Hi,

Is there any extensions included ? If yes, which ones ?

I would like to use SQLITE_ENABLE_JSON1 extension  and perhaps others accross all platform.

Is it possible to activate some SQLite extensions ? I yes, how ?

Thank you

**Comment by simolus3** [comment]
Hi,

the `sqlite3` package can't make any guarantees about available extensions since it doesn't define how sqlite3 is actually loaded.
If you're using `sqlite3_flutter_libs`, the `json1`, `fts5` and `rtree` extensions should be available. This is what we're using on Android: https://github.com/simolus3/sqlite-native-libraries/blob/0e4353a6a7b80595928436191e03719a3edc6751/sqlite3-native-library/cpp/CMakeLists.txt#L30-L32 And this is what we're using on iOS: https://github.com/simolus3/sqlite3.dart/blob/7a226a08993ac3374fb7ddb4fe62112d941dea61/sqlite3_flutter_libs/ios/sqlite3_flutter_libs.podspec#L21-L24

**Comment by MobiliteDev** [comment]
Thank you very much for your answer
