### ISSUE TITLE
Possible to import Sqlite3 databases between OS files and WasmSqlite3 IndexedDbFileSystem

### ISSUE THREAD

**Issue by trhagado** [simolus3/sqlite3.dart#263]
I have a desktop Sqlite3 (no Drift) Flutter app that I'm trying to port to Flutter Web along with a set of regular OS Sqlite3 databases. It would be helpful if there was a way to move existing Sqlite3 OS files back and forth to and from the WasmSqlite3 IndexedDbFileSystem. I've looked at the source code a bit and can see how to read the raw database bytes from the IndexedDbFileSystem (e.g. https://github.com/simolus3/sqlite3.dart/issues/261) that I can then write to an OS file but can't see how to write a Uint8List of bytes from an OS database file into an WasmSqlite IndexedDB file. Any guidance on this would be appreciated.

**Comment by simolus3** [comment]
Generally, the way to write files into a web file system looks like this:

```dart
final vfs = await IndexedDbFileSystem.open(dbName: 'sqlite3-example');

final Uint8List databaseContents;
final (:file, :outFlags) = vfs.xOpen(Sqlite3Filename('/database'), SqlFlag.SQLITE_OPEN_CREATE);
file.xWrite(databaseContents, 0);
file.xClose();
await vfs.flush();
```

How you obtain the database contents is another question, but you could probably use the file reader APIs to read them from a form or files being dragged into the website.

**Comment by trhagado** [comment]
With the code you supplied, I was able to get the import to work
well, thanks. I saw in the code comments for IndexedDB that "we maintain
the illusion of synchronous access by keeping
the entire database cached in memory and then flushing
changes asynchronously." It seems like this could become a limiting factor
for "large" databases that would be difficult to keep entirely in memory.
I know that there are a lot of complexities in dealing with the sync/async
issues around SQLite and the browser but have you considered supporting a
VFS that only keeps part of the database in memory as some of the wa-sqlite
POCs do?

**Comment by simolus3** [comment]
> but have you considered supporting a VFS that only keeps part of the database in memory as some of the wa-sqlite POCs do?

We have three VFs implementations at the moment:

1. The (kind of unsafe) IndexedDb-based one.
2. `SimpleOpfsFileSystem`: This one is kind of similar to the sahpool VFS, except that it only supports a single database (you can use multiple `SimpleOpfsFileSystem`s if you need more than one). It doesn't have an internal cache and is quite fast, but doesn't support multiple tabs to open the database at the same time. It can only be used on workers (but packages like `drift` or `sqlite3_async` can host that worker for you and give you direct access).
3. `WasmVfs`: This one is similar to the default VFS from the SQLite WebAssembly build. It uses a workers with a shared buffer to synchronize requests.

I'm not aware of a VFS approach that is substantially better than these options. The one based on IndexedDb is the easiest to use since it doesn't require any workers, depending on browser features and whether you can afford to turn on COOP + COEP, there are also options that don't require any in-memory caching.

**Comment by rhashimoto** [comment]
> I'm not aware of a VFS approach that is substantially better than these options.

Have you considered [this approach](https://github.com/rhashimoto/wa-sqlite/discussions/157)? It has about the same performance as a pre-opened access handle VFS on a single connection, but also allows multiple connections.

**Comment by simolus3** [comment]
I like the idea of returning `SQLITE_BUSY` in the VFS, catching that exception in the wrapper, awaiting the promise and then re-trying.
In my case, the `sqlite3` package has the added challenge of sharing interfaces between the web variant and native code (so our equivalent of `step` can't return a promise / future). There's a web-specific package that also abstracts over workers and could support a VFS like this though.
