### ISSUE TITLE
Could not resolve sqlite3-native-library with old version of package

### ISSUE THREAD

**Issue by flankb** [simolus3/sqlite3.dart#51]
Hello!
I am trying to build an application (for Android) with an old version of the library (0.2.0). I get errors in the console:
```
Could not resolve all task dependencies for configuration ':sqlite3_flutter_libs:debugCompileClasspath'.
   > Could not resolve eu.simonbinder:sqlite3-native-library:3.32.3.
     Required by:
         project :sqlite3_flutter_libs
      > Could not resolve eu.simonbinder:sqlite3-native-library:3.32.3.
         > Could not get resource 'https://dl.bintray.com/sbinder/sqlite3-native-library/eu/simonbinder/sqlite3-native-library/3.32.3/sqlite3-native-library-3.32.3.pom'.
 > Could not GET 'https://dl.bintray.com/sbinder/sqlite3-native-library/eu/simonbinder/sqlite3-native-library/3.32.3/sqlite3-native-library-3.32.3.pom'. Received status code 403 from server: Forbidden
```
I have next dependencies in `pubspec.yaml`:

```
environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  moor: ^3.3.1
  sqlite3_flutter_libs: ^0.2.0
```

The reason I am building the old version is to test the transition from the old version to the new one with null-safety.

**Comment by simolus3** [comment]
The old version was hosted on Bintray, which has since been shut down. This is why newer versions are hosted on Maven central, which required an update to the package. I think you should just use the newer version.

> The reason I am building the old version is to test the transition from the old version to the new one with null-safety.

`sqlite3_flutter_libs` has no dependencies outside of Flutter, and the old version did not contain any Dart code to import. I think you can safely use the old version for null-safety testing.
