### ISSUE TITLE
Creates resources for all platforms for appbundle

### ISSUE THREAD

**Issue by cedrickrusche** [simolus3/sqlite3.dart#9]
For sqlite3_flutter_libs the library generates resources for all platforms (arm64-v8a, armeabi-v7a,  x86, x86_64) in one appbundle regardless what is specified via "flutter build appbundle --target-platform".

This is a major problem because Google think that the app works on all these platforms but at the moment flutter cannot create the resources for x86 and the app does not start after the installation on these platforms.

pub.dev version of library 0.2.0

* Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19042.572], locale de-DE)
* Android toolchain - develop for Android devices (Android SDK version 28.0.3)
  *  Platform android-29, build-tools 28.0.3

**Comment by kuhnroyal** [comment]
Can you try using abiFilters on the Gradle side? Seems to work for me but I am not using `--target-platform`.
```
ndk {
    abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
}
```

**Comment by simolus3** [comment]
The problem is that, with some trickery, it [_is_ possible](https://github.com/flutter/flutter/wiki/JIT-Release-Modes) to run Flutter on x86 devices. If this library applied an `abiFilter`, we'd break those applications.

I added a section to the readme explaining the problem and suggesting to apply `abiFilters`. It's unfortunate that the current situation requires adaptions for the majority of users, but my understanding is that we can't add `abiFilters` without irrevocably breaking some users :( If there's something this library could do, I'm happy to add that feature.
